girder/girder_web_components

package.json
src/App.vue
src/rest.js
yarn.lock

The main purpose of this topic is to decide on two runtime libraries that we'll use for REST interaction, my suggestions being:
* [axios](https://github.com/axios/axios) for dealing with XHRs
* [js-cookie](https://github.com/js-cookie/js-cookie) for dealing with cookies
As you can see from the yarn.lock changes, they don't introduce any new transitive dependencies, and they're both light, modern, popular, and well-documented.
In addition to selecting these tools, there is a minimal REST class that I envision we will use via Vue's `provide/inject` framework, e.g. 
```
import RestClient from 'girder/rest';
...
// ancestor
provide: {
girderRest: new RestClient()
}
...
// descendant
inject: ['girderRest'],
created() {
this.girderRest.request.get('collection').then(...)
}
```

REST client utility

---

README.md
package.json
src/components/index.js
src/index.js
src/main.js
src/utils/index.js

The `build` command now builds a UMD library target rather than the example app (which will still be what you see via `yarn serve`, though we can certainly add another script for building the example).
In addition to being able to import this into node or a downstream webpack build, this means the library can now be imported into the browser directly, as in the following example, which was working when I included the App.vue component in the library exports.
```
<meta charset="utf-8">
<title>girder demo</title>
<script src="https://unpkg.com/vue"></script>
<script src="./girder.umd.js"></script>
<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
<link rel="stylesheet" href="./girder.css">
<div id="app"></div>
<script>
const …
```

Build this library as a UMD module

---

package.json
src/utils/s3.js
src/utils/upload.js
tests/unit/uploadS3.spec.js
tests/unit/uploadUtil.spec.js
yarn.lock

This adds some unit testing of the upload module, and attempts to establish some practices surrounding mocking. I've chosen to use the [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter) package rather than the more first-class [moxios](https://github.com/axios/moxios) because it seems nicer to use and is also more popular.
Naturally, adding testing did uncover an actual bug, on which I'll comment inline.

Upload module testing

---

.circleci/config.yml
package.json
src/App.vue
src/components/Upload.vue
tests/unit/.eslintrc.js
yarn.lock

Unfortunately, the vue-cli-service tooling provides no support for linting pug templates, and has no plans to at the moment, though [open issues exist](https://github.com/vuejs/eslint-plugin-vue/issues/310), and I imagine it will be added at some point in the future.
I think we should add some third party tooling to support this for the moment. Yes, this adds an annoying amount of dev dependencies and departs slightly from the world of pure first-class vue-supported tools, however I think it's important enough as we gain momentum writing components to justify this.
It's clear that code review time is one of our most limited resources, and we know that using humans as linters in code review is an anti-pattern / bad practice. So with that in mind, I think we should merge this, and open an …

Lint pug templates in Vue components

---

package.json
yarn.lock

This will allow us to use the vue-sanctioned best practices
for pug support without having to worry about it ourselves.

Use vue-cli-plugin-pug

---

tests/unit/Authentication.spec.js
tests/unit/utils.js

@subdavis @jbeezley this is the fix for the weirdness in the test we saw earlier today. That one liner in `utils.js` is functionally equivalent to the `flush-promises` package.

Add working nextTick helper and test utils module

---

package.json
src/App.vue
src/components/Authentication/Authentication.vue
src/components/Authentication/Login.vue
src/components/Authentication/Register.vue
src/index.js
src/rest.js
tests/mocks/stub.js
tests/unit/Authentication.spec.js
tests/unit/Upload.spec.js
tests/unit/utils.js
yarn.lock

Use the vue-async-computed library

---

src/components/Upload.vue

44ba491 fixes #44 by wrapping the top level components in a `v-layout(column)`.
6fa93ab fixes a different bug that was introduced on #43 that was causing the message not to be vertically centered when the component was not rendered in fullscreen mode, e.g. inside a dialog.

Upload component scroll bug

---

src/components/DataBrowser.vue

@subdavis PTAL, I couldn't determine what effect the `elevation-1` class was intended to have on this component, removing it didn't change anything that I could find. If there's a reason for it I will put it back.

Fix styles on data browser component

---

src/App.vue
src/components/Authentication/Login.vue

Currently after login/logout, a user's password still exists in component state and can be retrieved with console access.
This adds 2 redundant behaviors:
* On successful login, the component will automatically clear the password field.
* On session change (such as a login) the entire component will be destroyed.   I think this is a good practice to also clear the username field and whatever other state has accumulated, but there may be reasons not to do this, so the decision is left up to the app developer.

Auth should forget password after successful login or session change.

---

src/.eslintrc.json

As promised, here's a linter rule that ensures we don't use the `@` alias within the `src` directory. Since the `vue-cli-service lint` command also lints the test directory, and we need that alias there, this rule cannot be applied to all directories. I assume it's also possible to put this in package.json and just override it in the test dir and any other dirs we need it, but this feels easier.

Disallow '@' alias for local imports in src tree

---

.env
.env.production
.gitignore
README.md
demo/App.vue
demo/main.js
package.json

* Gitignore built demo site files
* Move demo site files to a separate directory
* Set demo app API root from environment
* Ensure demo files are linted
* Default "vue-cli-service lint" paths are in: https://github.com/vuejs/vue-cli/blob/v3.0.4/packages/@vue/cli-plugin-eslint/lint.js#L18
Fixes #77

Separate demo

---

src/components/UpsertFolder.vue

Would resolve https://github.com/girder/girder_web_components/issues/89
I personally like browser autocomplete so I enabled autocomplete on the folder name. If we like it we could potentially enable on all common input fields, if not I can remove the autocomplete.

Use submit event and enable browser autocomplete

---

package.json

Refs #95. We don't need this rule right now, and I propose removing it globally in favor of inline overrides.

Remove unused style rule

---

src/components/Presentation/Dropzone.vue
src/components/Upload.vue

When using the Upload component, the business case would like to limit what kind of file is allowed to be uploaded. 
Resolve https://github.com/girder/girder_web_components/issues/101

Add accept prop to Upload and Dropzone components

---

demo/App.vue
src/components/DataBrowser.vue
src/components/Presentation/DataTable.vue

This feature was requested by @zackgalbreath and was pretty trivial to implement.
* Add dragability for rows in DataTable.vue
* Upstream is expected to register and use these rows with some dropzone.
* New events:  DataBrowser and DataTable both emit:
* drag
* drop
* dragstart
* dragend
* New props:
* DataBrowser gets `draggable: Boolean`
* DataTable gets `draggable: Boolean`
Those event payloads are structured `{ items: Array<{ index, item, selected }>, event: <native event> }` .
@zackgalbreath will this suit your use case?  I actually really like this as a feature and I may be able to use it myself soon.

Adds draggability flag

---

src/rest.js

* Rename the RestClient `cors` parameter to `setLocalCookie`
* This is a more accurate description of its behavior.
* Add a `withCredentials` parameter to RestClient
* This will send all XHR requests with this option.

Improve handling of cookies with CORS requests

---

README.md

This resolves some incorrect or missing information, while refocusing the user documentation as a quickstart guide for typical usage.

Rewrite the README user documentation

---

src/components/Upload.vue
src/utils/upload.js
tests/unit/uploadS3.spec.js
tests/unit/uploadUtil.spec.js

This isn't intended to be merged as is, just to show a rough idea of what I'm talking about on #94.
With this interface, downstreams could subclass the Upload class and pass it into the Upload component to control behavior. This also adds 3 hook points into the upload class that are no-ops by default. These hooks would allow things like:
* Perform an action (synchronous or asynchronous) before the first upload.
* Perform an action before *each* upload, or only certain uploads, based on filename or other file properties of the file.
* Perform an action after the *last* upload is done.
* Perform an action if an error occurs during upload.
If we allow these hooks to return values, they could also be used to further augment the behavior of the component, e.g. skipping certain files, or …

Upload subclassing

---

src/components/Presentation/DataTable.vue

When `selectEnabled == false`, make the entire row clickable.
More changes for #103

Make entire row clickable when selectEnabled = false, emit rowClick

---

src/components/Upload.vue
src/index.js
src/utils/UploadBase.js
src/utils/upload.js

This PR includes a few improvements.
* Add back `preUpload`, `postUpload` callbacks. Because (1) The demo app is using these callback, the demo app is broken and won't refresh the file list after upload at this moment. (2) The context of these callbacks is the parent Vue component of Upload.vue. the context `afterUpload`, and `beforeUpload` is the upload class. Without hacking, It's way easier to consume the callback in the parent component with these callbacks. (3) `afterUpload`, and `beforeUpload` is for the individual file. `preUpload`, `postUpload` is for all of the uploads. Take the demo app as an example. It's meant to refresh after the whole upload process. Again, without hacking, these are easier to work with. 
* This line …

Upload class optional members

---

src/components/Search.vue

This PR internalize the DebounceCounter helper variable to an individual instance of the Search component. Even though I don't see we could run into issues in a short time with the current implementation, but this change prevents potential weird behavior and anti-pattern and help me monkey patch this Search in a downstream application.

Internalize helper variable

---

src/rest.js

This is now the preferred header for the latest upstream Girder, but it is also backwards compatible with previous Girder versions.

Use "Authorization" header to login to Girder

---

README.md
package.json
src/index.js
src/utils/vuetifyConfig.js
yarn.lock

See: https://vuetifyjs.com/en/framework/a-la-carte#importing-components
Since this allows Webpack's tree-shaking to occur, this reduces the size of the resulting UMD library and demo app by ~40%.
Here's the specific results of applying this change:
Before: `build`
```
File                      Size                     Gzipped
dist/girder.umd.min.js    645.97 KiB               159.85 KiB
dist/girder.umd.js        1490.58 KiB              284.00 KiB
dist/girder.common.js     1490.12 KiB              283.83 KiB
dist/girder.css           358.94 KiB               53.17 KiB
```
Before: `build:demo`
```
File                                    Size              Gzipped
_site/js/chunk-vendors.09a74c68.js      657.34 KiB        168.95 KiB
_site/js/app.340b2dbd.js                56.74 KiB …
```

Import Vuetify as a module, reducing size

---

demo/App.vue
demo/main.js
package.json
src/components/index.js
src/components/job/FilterForm.vue
src/components/job/JobList.vue
src/components/job/JobTable.vue
src/components/job/index.js
src/components/job/status.js
tests/unit/job/FilterForm.spec.js
tests/unit/job/JobList.spec.js
tests/unit/job/JobTable.spec.js
tests/unit/job/Status.spec.js
vue.config.js
yarn.lock

This ports the Job Listing components from https://github.com/Kitware/resonantgeo
The development ResonantGeo will focus on Geospatial components and won't have the Job Listing components.
However, at this moment, Vigilant is using the Job Listing component, so it is important to have it moved to here and merge this sooner rather than later.

Migrate Job listing components from other repo

---

demo/App.vue
src/components/Breadcrumb.vue
src/components/DataBrowser.vue
src/components/Presentation/DataTable.vue
src/components/Search.vue
src/components/UpsertFolder.vue
src/utils/createLocationValidator.js
tests/unit/Breadcrumb.spec.js
tests/unit/DataBrowser.spec.js

This PR 
- Fix an issue related to breadcrumb. 
- Improved the girder-breadcrumb component. There always has been console warnings complaining about deprecated slot usage with v-breadcrumb. This commit fixes that issue and prepared for the new slot syntax. This commit also fixes a couple of issues introduced in the previous PR.
- Makes boolean props always negate its default value, so their default value can be deduced from the naming itself, and that when using the props, only the name is needed.
This commit also removes a couple of unused props. e.g. one of the props was called newFolderEnabled but it has a default value of true, so, it has to be set as :new-folder-enabled='false' to use it. It has been renamed to `new-folder`, to indicate it's default value is false, and when using, …

Update boolean props

---

README.md
vue.config.js

I've gone ahead and cut over the pages site to gwc.girder.org to trigger certificate generation on github's side.  I _think_ this is configured correctly, but we'll just have to wait and see.
Meanwhile, these changes are needed.

Serve from root

---

public/CNAME

Turns out that UI element was actually generating the CNAME file and committing it to the gh-pages branch which our CI overwrites with a force push.  Silently committing from github settings UI seems like a terrible design choice, but whatever.  
Here's the fix.

Add cname file

---

src/components/Authentication/Authentication.vue
src/rest.js

Nothing too special here.  Worth noting that I think it's sufficient to do a rewrite on the `location.hash` of the page after getting the token from there.  This library isn't in control of page location, so there may be virtual hash routes from a vue router we don't want to change.
Here's a complex example:
```text
// before redirect
http://origin.com/path?query#/virtual/path#girderToken={girderToken}__
// after first redirect @ girder, girder fills the template string.  It may also append whatever other noise it wants -- that's the reason for the suffix.
redirect_to = http://origin.com/path?query#/virtual/path#girderToken=tokenstring__#other/stuff?
// after GWC has loaded, location should look like this:
http://origin.com/path?query#/virtual/path#other/stuff?
```
fixes #73

Token from oAuth reply

---

src/components/Upload.vue

A customer adamantly wants a different phrase for that button.  This seems like a low maintenance burden.

Allow upstream to specify upload phrase

---

src/components/Authentication/Authentication.vue
src/components/Authentication/Login.vue

In some cases (e.g. pluggable auth on the backend), downstreams won't want a forgotten password flow to go through Girder at all. Or, like in my case, the app just isn't mature yet so there isn't a forgot password view.

Prop in Auth and Login components to hide Forgot Password

---

src/components/DataDetails.vue

Use `iconKey` to lookup the icon in the vuetify config, or `icon` to pass the raw string value.

Support keyed and raw icon identifiers in DataDetails action list

---

src/components/DataDetails.vue

Fix metadata alignment

---

src/components/Presentation/FileUploadList.vue

Not sure why that was ever there in the first place.  Breaks everything when the height of the container is explicit.

bugfix remove height 100%

---

src/components/Search.vue

Since the vuetify upgrade, the skeleton was broken.  This fixes it.

bugfix quick results skeleton

---

.circleci/git-config.sh
.circleci/npmjs-publish.sh
.circleci/pages-deploy.sh

npm deployment now works, which is nice.   
You'd think CircleCI would provide better mechanisms for this sort of thing.

Fix CI post-release tagging.

---

src/components/DataBrowser.vue
src/components/Presentation/DataTable.vue
src/components/Snippet/FileManager.vue
tests/unit/DataBrowser.spec.js

This is a feature requested by a downstream project https://github.com/dandi/dandiarchive/issues/42
It looks like a good feature to have to GWC. However, am not sure if the effort and (technical debt) to implement reactive itemsPerPage can be justified, so the itemsPerPage prop only controls initial size. 
I'll be adding a test case for it, any comment or feedback is welcomed.

Add props to control browser page size

---

src/components/Upload.vue
src/utils/mixins.js

in #200 I made upload functionality into a mixin and factored `upload.start()`'s parameters from instance properties into explicit function properties.  I overlooked `dest`.
This had the interesting effect of allowing the `preUpload` function to set dest.  While I think that's a good capability, it relies on the developer knowing a little too much about the reactivity system and the JS event loop for my liking.  If `dest`  is a prop of the upload component and is modified during `preUpload` it's hard to reason about the race between the dest update and the `start` func arriving at this block:
```js
file.upload = new uploadCls(file.file, {
$rest: this.girderRest,
parent: this.dest,
progress,
});
```
TL;DR; there's too many moving parts for a developer to be confident that `dest` will win …

Make dest a param of upload.start

---

src/components/DataBrowser.vue
src/components/Presentation/DataTable.vue
src/components/Snippet/FileManager.vue
tests/unit/DataBrowser.spec.js

While I was trying to add support for 'all' page size. 
I noticed that the browser makes unnecessary requests to folder or items under certain conditions, so I refactored the code to handle those conditions.
This PR also update default page sizes.
Resolve https://github.com/girder/girder_web_components/issues/205

Fix issue that data browser don't handle page size 'all'

---

src/components/DataBrowser.vue
src/components/Presentation/DataTable.vue
src/components/Snippet/FileManager.vue

This would allow the use of DataTable in a more customized way like this
Specifically, there is a downstream project that needs to distinguish folder navigation and opening the video clip within the folder.

Add an additional slot to DataTable

---

package.json
yarn.lock

From a fresh clone I was not able to run any unit tests on my laptop.
https://github.com/facebook/jest/issues/6913#issuecomment-423660110
I ran:
```
yarn remove babel-jest
yarn add babel-jest -D
```
and the issue went away.  I don't understand how tests can be passing on CI and my desktop but be broken from my laptop (same version of node, npm, yarn).  
/shrug
```
FAIL  tests/unit/job/Status.spec.js
● Test suite failed to run
Cannot find module '/home/brandon/github.com/girder_web_components/node_modules/@babel/runtime/helpers/builtin/interopRequireWildcard' from 'Status.spec.js'
1 | import * as status from '@/components/Job/status';
2 | 
> 3 | describe('job/status', () => {
|                               ^
4 |   it('get a built in status by key', () => {
5 | …
```

Version incompatibility jest#6913 ?

---

demo/App.vue
package.json
src/components/DataBrowser.vue
src/components/Presentation/DataTable.vue
src/utils/vuetifyConfig.js
tests/unit/utils.js
yarn.lock

I feel like every successive update turns vuetify into a more and more quirky codebase, and I'm really starting to wonder if they've just lost control of the scope of the project and the organization is insufficient for the complexity they're managing.
I talked to Jared for a while and we are both really disappointed by the rigidity and high cognitive load of the v-row and v-col grid system compared to v-container and v-layout.  I'm about 1 free afternoon away from trying to replicate the 1.X v-container and v-layout components clean-room style in pure flexbox CSS.  Prepare yourselves for girder-container and girder-layout.
I also don't know how it makes sense that, if I specify a slot for the header, I also have to remember to disable the default header or else I get 2 headers.  That's …

upgrade to vuetify 2.2.4

---

demo/App.vue
demo/Headline.vue
src/components/index.js
src/utils/vuetifyConfig.js

This PR makes changes to the demo application.
I've found recently that when trying to explain girder web components, showing people the demo, which looks like a normal application, is confusing.  It's hard to explain to someone who isn't already a Vue developer what the "components" are and how they could be useful within your application.
I've also found that people are confused about what exactly this package offers.  Is it just a login box and the data browser? 
This PR seeks to make the demo app less of a "sample implementation" and more like interactive documentation. I'm really fond of what Vuetify has done, and that's the spirit of what I'm trying here.
I'm not done yet, and I didn't want to spend long on this (took about an hour), but hopefully this gives you an idea.
My end goal …

Interactive documentation

---

demo/App.vue
demo/Headline.vue
demo/NavLink.vue
package.json
src/components/Job/FilterForm.vue

This also contains a couple minor tweaks to the demo page, and
changes the job list component to say just "Jobs" instead of
"Girder Worker Jobs" since jobs are technically independent of
Girder Worker.

Add ToC to demo app

---

.vscode/settings.json
demo/App.vue
demo/Headline.vue
demo/NavLink.vue
src/components/AccessControl.vue
src/components/Authentication/Authentication.vue
src/components/Authentication/Login.vue
src/components/Authentication/OAuth.vue
src/components/Authentication/Register.vue
src/components/Breadcrumb.vue
src/components/DataBrowser.vue
src/components/DataDetails.vue
src/components/Job/FilterForm.vue
src/components/Job/JobList.vue
src/components/Job/JobTable.vue
src/components/Markdown.vue
src/components/MarkdownEditor.vue
src/components/Presentation/DataTable.vue
src/components/Presentation/DetailList.vue
src/components/Presentation/Dropzone.vue
src/components/Presentation/FileUploadList.vue
src/components/Search.vue
src/components/Snippet/FileManager.vue
src/components/Upload.vue
src/components/UpsertFolder.vue

Turns out autoformatting is hard.
* https://github.com/vuejs/vetur/issues/695 -- Vetur doesn't support a single autoformatter that is capable of running `eslint --fix` with our configuration.  You can try to find a prettier config that happens to overlap, but I don't believe it's possible.
* As a result, I've turned js autoformatting with vetur off for VS Code.  Eslint is much smarter than any prettier config.
* However, I did turn on lint-on-save features, which do read `eslintConfig` from package.json.  It's basically like running `yarn lint` every time you save
HTML formatting was another animal. Eslint isn't that opinionated about html formatting, and I think we should be more rigorous when possible.
For example:
```html
<v-tab-item key="login-box">
<girder-login …
```

Autoformatting with js-beautify-html

---

README.md
package.json
src/components/index.js

Because we're using vuetify-loader now, that import was unnecessary.  If a consumer wants to use this without vuetify-loader, importing the stylesheet will be their problem.

Remove unnecessary import

---

src/components/DataDetails.vue
src/components/Presentation/DetailList.vue

In order to make the `View Item`, `Download`, and `Download (zip)`
actions more useable, embed their text into a link rather than
exclusively rely on using click events. This allows users to open them
in a new tab or copy the link address.
Closes #225
Also closes dandi/dandiarchive#82
Deprecates #252

Make download actions links

---

package.json
src/utils/mixins.js

When uploading files `dest` gets set before the `preUpload` function can make any changes to `dest`. This change will allow `preUpload` to potentially update `dest`, while keeping `dest` the same if `preUpload` does not make any updates to it.

Allow preUpload to update dest

---

package.json
src/components/Upload.vue

I've got a downstream app that is making use of a custom upload drop zone. Exposing these props to the slot makes things a lot more straightforward; without them I have to hack a few things.

Bind useful props to dropzone slot

---

dkc/views/Browse.vue
src/components/DataBrowser.vue

I noticed that the DataBrowser was sending duplicative XHRs, which I found out was resulting from the asyncComputed getter being fired multiple times even though the values hadn't changed. After fighting with asyncComputed for about 2 hours, I gave up on it and just did it the normal, more procedural way and everything worked fine.
This also fixes an issue of too-aggressively refreshing based on the pagination options watch.

Fix duplicate XHRs resulting from asyncComputed

---

src/utils/mixins.js

@subdavis this is a follow-up to #283 to use one of the alternative approaches I mentioned. I tried it using both the generator, and the index variable in closure, and ended up using the simple closure-based one. The generator one felt like overkill for the case of normal iteration over an array.
In addition to that change, I removed the unnecessary `promiseList` -- if I understand correctly, it was redundant since `await`ing the return value of `uploadFile` will already resolve to the result. Please correct me if there's something I'm missing there.

Simplify upload worker pool code

---

src/components/Presentation/FileUploadList.vue

Noticed this while testing the recent uploader changes. Really long filenames were overflowing the container of the FileUploadList. Before:
After:

Fix overflow style bug in FileUploadList

---

src/components/Presentation/Dropzone.vue

I've been staring at the upload component a lot lately in a few different app contexts, and I just felt like it needed a little bit more of a call to action when it was in the waiting for files state. I've seen some other drag and drop upload UIs that show a little frame around the corners of the drop zone, and tried it out here. Let me know what you think.

Add some flair to the upload drop zone

---

src/components/Upload.vue

This addresses one other qualm I've been having with the upload component, which was that it was visually jarring when switching between the dropzone and the files list. A simple transition makes this a lot better IMO (GIF framerate probably doesn't do it justice).

Add transition between upload dropzone and file list

---

package.json
src/components/Presentation/Dropzone.vue
src/components/Upload.vue

I ran into an issue using this downstream, where trying to have a larger height component caused a bunch of blank space to appear between the actions and the file list. This was due to an empty `v-col` that was apparently set to grow.
I can't figure out why the `v-row` or `v-col` were even present before. Removing them doesn't break anything that I can see currently.
Screenshot of problem:

Remove layout weirdness from Upload component

---

README.md
package.json
src/components/index.js
src/index.js

#293 broke CSS.  See gwc.girder.org - didn't notice locally because this optimization is disabled in dev mode.
This fix is related to https://github.com/vuejs/vue-loader/issues/1435, which is described as "undocumented". /shrug

Fix CSS tree shaking

---

README.md
package.json

Made both Vue and Vuetify peer dependencies.
Had to change the install guide to explicitly install vuetify, and realized I was just replicating Vuetify docs inline.
So I switched to recommending `vue add vuetify` as the install mechanism, since it does quite a lot of work that a user would otherwise have to guess from looking at the GWC package json and vue.config.js
This way, for the most common case of "fresh project", you get a more first-class vuetify experience rather than trying to replicate our config by hand.

Better document vue/vuetify installation

---

package.json

deploy changes from #293 
* Components explicitly renamed to `Girder*`.  No need to rename on import
* All imports provided from project index.  No need to provide path within library.
* registerComponents helper function
* typescript type definitions
**Old**
``` js
// Plugin, RestClient, Vuetify
import Girder, { RestClient, vuetify } from '@girder/components/src';
// Components
import { Authentication as GirderAuthentication } from '@girder/components/src/components'
```
**New**
``` js
// Plugin, RestClient, Vuetify
import Girder, { RestClient, vuetify } from '@girder/components';
// Components
import { GirderAuthentication } from '@girder/components';
```
Adds a simple helper function to register the main components globally, so you can do this:
``` js
// main.js
import { …
```

version 3.0.0
