- .gitignore
- package.json
* Specify env: browser in eslint config
* Remove bad practices from gitignore
> Tweaks to vue-cli generated code

- package.json
- src/utils/notifications.js
- tests/unit/.eslintrc.js
- tests/unit/notification.spec.js
- yarn.lock
This is adapted from the ResonantGeo version
> Notification bus utility

- src/rest.js
- src/utils/notifications.js
- tests/unit/notification.spec.js
> Make RestClient an event bus

- README.md
- src/components/index.js
- src/index.js
- src/main.js
- src/utils/index.js
- src/utils/vuetifyConfig.js
@jbeezley PTAL, this follows our discussion from this morning. The first commit here represents the code changes; if you approve of those, I'll add a second commit for the documentation that is relevant to downstreams.
@subdavis PTAL
> Create a Vue plugin for this library

- .circleci/config.yml
- package.json
- src/App.vue
- src/components/Upload.vue
- yarn.lock
This resolve issue https://github.com/girder/girder_web_components/issues/41
I added linting ability as suggested by @zachmullen, but I failed to make the configuration part of the package.json like other options do. (Probably needs to modify the plugin  to support that)
> Switch to SCSS

- package.json
- yarn.lock
There are many fixes and new features in recent Vuetify releases.
It's probably a good thing to keep track of the latest in general.
> Upgrade to latest Vuetify

- src/App.vue
- src/components/Breadcrumb.vue
- src/components/DataBrowser.vue
- src/components/UpsertFolder.vue
- tests/unit/Breadcrumb.spec.js
- tests/unit/FileBrowser.spec.js
- tests/unit/UpsertFolder.spec.js
> Fix Object Schema #48

- package.json
Once this gets merged I will publish a new release for downstreams pulling from the npm index.
> Alpha 2 release

- src/constants.js
- src/index.js
- src/utils/mixins.js
The second commit also adds a mixin. I'm happy to separate these commits into different PRs if people prefer.
> Add useful constants to the library

- src/components/UpsertFolder.vue
I must have forgotten to wire up the markdown editor.
> Wire up Description to Folder Upsert

- src/App.vue
- src/components/Authentication/Login.vue
- src/components/Authentication/Register.vue
- src/rest.js
- src/utils/vuetifyConfig.js
- tests/unit/Register.spec.js
This PR handles **admin approval required** and/or **email verification required** registration by simply give a generic message.
This PR also address two related small issues and added a minimal test to the Register component.
> Handle admin approval registration

- README.md
Update readme to mention demo.
> Update README with references to web

- src/utils/mixins.js
> fix for building girder web components from external app

- yarn.lock
Pull merge up to version 1.2.1.
> pull merge up to version 1.2.1

- package.json
- src/components/Presentation/DataTable.vue
> Range select in Data Browser

- src/components/Presentation/FileUploadList.vue
- src/components/Upload.vue
Work in progress.
Block on #154
> Allow the consumer to inject widgets into each row of an upload file list.

- src/components/Job/JobList.vue
- src/components/Job/JobTable.vue
This will be blocked on the vuetify upgrade, but I needed a way to add an additional cell to job rows.
Block on #154
> Allow adding additional slots into the job table

- src/rest.js
I don't like adding this back, but I can't function without it.  As long as girder supports this auth mechanism, I feel like having the option to use it is within scope here.
> Add option to use Girder-Authorization for auth.

- README.md
Adds back some changes from #157 that got lost.
> Document sass-loader version incompatibility

- .circleci/config.yml
- package.json
I'm tired of not having this :P
> npmjs deployment with circleci

- demo/App.vue
Since this demo app is highly likely to be used as a canonical example for downstream apps, we should make it adhere to vuetify best practices, which I admittedly am not an expert on. However, these two changes do seem to be in line with their recommendations.
> Use best practices for app layout in demo app

- .circleci/config.yml
- .circleci/npmjs-publish.sh
- README.md
closes #168 
Need to verify that sed, awk, tr, grep, etc. are all installed on the node:10 image from circleci
> Publish to npm on package.json version update

- demo/App.vue
- src/components/DataBrowser.vue
- src/components/DataDetails.vue
- src/components/Presentation/DataTable.vue
- src/components/Presentation/DetailList.vue
- src/components/Snippet/FileManager.vue
- src/components/index.js
- src/utils/mixins.js
- src/utils/vuetifyConfig.js
- tests/unit/DataDetails.spec.js
- tests/unit/utils.js
closes #163 #65 
I've been sitting on this branch a while, recently rebased it since everything else got merged.
It isn't ready to go in, but it is neat to play with as we talk about what else this library should have.  I think the introduction of this component exposes some of the weak points in the current state management since state flows between browser and details, and both can modify state.
After this component, I don't know what the next feature for this library will be.  It might be good to let it breathe and exercise it more as consumers from other apps to get a feel for what we've done well and what can be improved.
Feel free to browse through or totally ignore this PR.  I'm only opening it for the sake of sharing and discussion.
> Details View

- demo/App.vue
- src/components/DataBrowser.vue
- src/components/Presentation/DataTable.vue
- src/components/Snippet/FileManager.vue
resolves #172 #179
This is actually necessary to address needs in #179.  Without this change, it isn't possible for downstream to change the value of selected.
> Use v-model for data browser selected rows

- demo/App.vue
- src/components/Search.vue
closes #165 
Added an example usage to the demo app.  I can remove it if no value is added.
> Add search result slot with demo

- package.json
Test out the new CI deployment.
> release v2.0.2

- src/components/Upload.vue
I need this feature downstream so that I can preview a set of selected local files prior to them being uploaded.
> Add ability to get local files out of Upload component

- demo/App.vue
- src/components/Breadcrumb.vue
- src/components/DataBrowser.vue
- src/components/DataDetails.vue
- src/components/Job/FilterForm.vue
- src/components/Job/JobList.vue
- src/components/Job/JobTable.vue
- src/components/Presentation/DataTable.vue
- src/components/Presentation/DetailList.vue
- src/components/Search.vue
- src/components/Snippet/FileManager.vue
- src/components/UpsertFolder.vue
- src/utils/vuetifyConfig.js
This resolves https://github.com/girder/girder_web_components/issues/195
At this moment, many custom color tunings are removed to make it more generic.
Some ternary conditions in the template and stylesheet are added to address some key differences.
> Support Vuetify dark theme

- package.json
- src/components/AccessControl.vue
- src/components/Breadcrumb.vue
- src/components/DataBrowser.vue
- src/components/Presentation/DataTable.vue
- src/components/Search.vue
- src/components/Snippet/FileManager.vue
- src/components/index.js
- src/utils/vuetifyConfig.js
- tests/unit/AccessControl.spec.js
- tests/unit/DataBrowser.spec.js
- yarn.lock
The original PR is closed accidentally and can't be reopened.
https://github.com/girder/girder_web_components/pull/128
This has followed all the comment of the original PR.
This is ready to be reviewed.
> Initial access control

- src/components/Search.vue
Allow downstream to override the no-results row.
> Add slot for no results in Search

- src/components/AccessControl.vue
- src/components/Snippet/FileManager.vue
Fix the issue that the access control dialog shows on an item that doesn't permission
> Check permission before showing access dialog

- src/components/Presentation/Dropzone.vue
- src/utils/vuetifyConfig.js
> Dark theme support in Dropzone and switch in demo App

- .circleci/config.yml
This is a slow process because I can only test the changes once per release attempt.
resolves #217
> Add git ssh write-access key to publish key context

- package.json
- src/components/Job/JobProgress.vue
- src/components/Job/JobTable.vue
- src/components/Job/index.js
- src/components/Job/status.js
- src/utils/mixins.js
Factor Girder Job object formatter into a mixin and the JobStatus into a component so I can show the status of a single job in consumers.
> Girder Jobs Status component refactor and JobFormatter mixin

- package.json
- src/utils/mixins.js
Adds results argument to postUpload
> Results postupload

- package.json
- src/components/Presentation/FileUploadList.vue
- src/components/Upload.vue
- src/utils/mixins.js
- src/utils/s3.js
Still testing, but this is more or less done.
closes #231
> Parallel upload of files to girder

- .circleci/config.yml
- .vscode/settings.json
- README.md
- demo/App.vue
- demo/Headline.vue
- demo/NavLink.vue
- package.json
- src/components/AccessControl.vue
- src/components/Authentication/Authentication.vue
- src/components/Authentication/Login.vue
- src/components/Authentication/OAuth.vue
- src/components/Authentication/Register.vue
- src/components/Breadcrumb.vue
- src/components/DataBrowser.vue
- src/components/DataDetails.vue
- src/components/Job/FilterForm.vue
- src/components/Job/JobList.vue
- src/components/Job/JobTable.vue
- src/components/Markdown.vue
- src/components/MarkdownEditor.vue
- src/components/Presentation/DataTable.vue
- src/components/Presentation/DetailList.vue
- src/components/Presentation/Dropzone.vue
- src/components/Presentation/FileUploadList.vue
- src/components/Search.vue
- src/components/Snippet/FileManager.vue
- src/components/Upload.vue
- src/components/UpsertFolder.vue
- tests/unit/AccessControl.spec.js
- yarn.lock
> Use HTML for templates instead of pug

- demo/App.vue
- src/components/Presentation/DataTable.vue
> Include _id, _modelType in drop event payload.

- package.json
Merge after #237 and #240 
Minor breaking changes from 2.1.0, mostly related to #243
> Bump 2.2.0

- package.json
- tests/unit/Breadcrumb.spec.js
- yarn.lock
> Upgrade axios-mock-adapter and babel core

- package.json
- src/utils/mixins.js
> Support additional arguments for UploadCls

- package.json
vue/recommended is a superset of vue/essential rules.
> Remove vue/essential rule

- package.json
- yarn.lock
This could not be done on #266 due to an upstream eslint bug,
but that has since been fixed.
> Upgrade eslint package

- package.json
- src/utils/mixins.js
Limit upload concurrency to 5 requests.
This was pretty straightforward to change.
fixes #282
> Upload with limited worker pool

- index.d.ts
> Typo Dropzone

- src/components/Authentication/Authentication.vue
- src/components/Authentication/Login.vue
- src/components/Authentication/Register.vue
> Show better error for email verification required

- package.json
- src/components/Search.vue
See https://github.com/vuetifyjs/vuetify/issues/2792 for why I did the `Math.random()` hack.
> Search theme fix

- src/utils/mixins.js
I'm ditching the C-ish cleverness now that I've started showing this code to people as an example :)
> Improve readability of upload worker pool code

- src/components/Authentication/OAuth.vue
Complementary to girder/girder#3393
> Add a missing MS logo to OAuth widget
